server:
  port: 8061

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://postgres-task:5432/task_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-sv:8080/realms/master

# (lo mantengo tal cual)
#USER_MS_BASE_URL: http://user-ms:8071
USER_MS_BASE_URL: http://user-ms:8071

#registro y descubrimiento en Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}

#(útil para monitoreo)
management:
  endpoints:
    web:
      exposure:
        include: health,info