server:
  port: 8061

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  security:
   oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8095/realms/master
  
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true

USER_MS_BASE_URL: http://localhost:8071
